# Modelo SVM

### Equipo 4:
    Karla Andrea Palma Villanueva (A01754270)
    Viviana Alanis Fraige (A01236316)
    David Fernando Armendariz Torres (A01570813)
    Alan Alberto Mota Yescas (A01753924)
    Adrián Chávez Morales (A01568679)
    Jose Manuel Armendáriz Mena (A01197583)

In [ ]:
# Libraries used
import pandas as pd # Database
import numpy as np # Math
import matplotlib.pyplot as plt # Graphs
import random # Randomness
from sklearn.model_selection import train_test_split  # Splits data into training and test sets
from sklearn.svm import SVC # SVM method
from sklearn.metrics import classification_report, confusion_matrix # Evaluates the classification model

In [1]:
sd = 231 # Sets a seed value for the random number generator to ensure reproducibility
random.seed(sd)  # Initializes the random number generator with the specified seed

# Seeds used
### 222 ------ 78%
### 999 ------ 79%
### 256 ------ 77%
### 666 ------ 77%
### 365 ------ 79%
### 616 ------ 77%
### 236 ------ 78%

# Best seeds
### 231 ------ 80%
### 6   ------ 80%
### 625 ------ 80%
### 265 ------ 80%
### 606 ------ 80%



In [4]:
# Loas database
X = pd.read_csv("dfx.csv") # X cotains the features 
y = pd.read_csv("dfy.csv") # y is the target variable

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)  # Splits the dataset into training and testing sets
# 80% of the data is used for training and 20% for testing

In [16]:
# Training the algoritm
svclassifier = SVC(kernel = 'linear') # hyperparameter used: kernel
svclassifier.fit(X_train, y_train)

# Predictions
y_pred = svclassifier.predict(X_test)

# Evaluating the algoritm
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[88 15]
 [20 56]]
              precision    recall  f1-score   support

           0       0.81      0.85      0.83       103
           1       0.79      0.74      0.76        76

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179



In [7]:
svclassifier = SVC(kernel ='rbf') # hyperparameter used: kernel
svclassifier.fit(X_train, y_train)

# Predictions
y_pred = svclassifier.predict(X_test)

# Evaluating the algoritm
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[101   2]
 [ 67   9]]
              precision    recall  f1-score   support

           0       0.60      0.98      0.75       103
           1       0.82      0.12      0.21        76

    accuracy                           0.61       179
   macro avg       0.71      0.55      0.48       179
weighted avg       0.69      0.61      0.52       179



In [8]:
svclassifier = SVC(kernel ='sigmoid') # hyperparameter used: kernel
svclassifier.fit(X_train, y_train)

# Predictions
y_pred = svclassifier.predict(X_test)

# Evaluating the algoritm
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[70 33]
 [45 31]]
              precision    recall  f1-score   support

           0       0.61      0.68      0.64       103
           1       0.48      0.41      0.44        76

    accuracy                           0.56       179
   macro avg       0.55      0.54      0.54       179
weighted avg       0.56      0.56      0.56       179



c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
svclassifier = SVC(kernel ='poly') # hyperparameter used: kernel
svclassifier.fit(X_train, y_train)

# Predictions
y_pred = svclassifier.predict(X_test)

# Evaluating the algoritm
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[101   2]
 [ 62  14]]
              precision    recall  f1-score   support

           0       0.62      0.98      0.76       103
           1       0.88      0.18      0.30        76

    accuracy                           0.64       179
   macro avg       0.75      0.58      0.53       179
weighted avg       0.73      0.64      0.57       179



c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
